name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libwings-dev libgnome-menu-3-dev
             libcinnamon-menu-3-dev libmate-menu-dev bats
      - name: Build (gnome-menus)
        run: |
          ./autogen.sh
          ./configure
          make
      - name: Test (gnome-menus)
        run: |
          ldd wmgmenu | grep gnome
          make distcheck
      - name: Build (cinnamon-menus)
        run: |
          make distclean
          ./configure --with-cinnamon-menus
          make
      - name: Test (cinnamon-menus)
        run: |
          ldd wmgmenu | grep cinnamon
          make check
      - name: Build (mate-menus)
        run: |
          make distclean
          ./configure --with-mate-menus
          make
      - name: Test (mate-menus)
        run: |
          ldd wmgmenu | grep mate
          make check
