name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libgnome-menu-3-dev libwings-dev \
             gnome-menus cinnamon-common mate-menus
      - name: Configure
        run: ./autogen.sh && ./configure
      - name: Build
        run: make
      - name: Smoke tests
        run: |
          ldd wmgmenu | grep gnome
          ./wmgmenu
          ./wmgmenu -v
          ./wmgmenu --version
          ./wmgmenu -f gnome-applications.menu
          ./wmgmenu --filename gnome-applications.menu
          ./wmgmenu -f /etc/xdg/menus/gnome-applications.menu
          ./wmgmenu --filename /etc/xdg/menus/gnome-applications.menu
      - name: Distribution check
        run: make distcheck
      - name: Clean up
        run: make distclean
      - name: Install dependencies (cinnamon-menus)
        run: sudo apt install libcinnamon-menu-3-dev
      - name: Configure (cinnamon-menus)
        run: ./configure --with-cinnamon-menus
      - name: Build (cinnamon-menus)
        run: make
      - name: Smoke tests (cinnamon-menus)
        run: |
          ldd wmgmenu | grep cinnamon
          ./wmgmenu
          ./wmgmenu -v
          ./wmgmenu --version
          ./wmgmenu -f cinnamon-applications.menu
          ./wmgmenu --filename cinnamon-applications.menu
          ./wmgmenu -f /etc/xdg/menus/cinnamon-applications.menu
          ./wmgmenu --filename /etc/xdg/menus/cinnamon-applications.menu
      - name: Clean up
        run: make distclean
      - name: Install dependencies (mate-menus)
        run: sudo apt install libmate-menu-dev mate-menus
      - name: Configure (mate-menus)
        run: ./configure --with-mate-menus
      - name: Build (mate-menus)
        run: make
      - name: Smoke tests (mate-menus)
        run: |
          ldd wmgmenu | grep mate
          XDG_MENU_PREFIX=mate- ./wmgmenu
          ./wmgmenu -v
          ./wmgmenu --version
          ./wmgmenu -f mate-applications.menu
          ./wmgmenu --filename mate-applications.menu
          ./wmgmenu -f /etc/xdg/menus/mate-applications.menu
          ./wmgmenu --filename /etc/xdg/menus/mate-applications.menu
